#!/bin/bash
alias gitnotes="e ~/unix_settings/notes/git.md"
alias hgnotes="e ~/unix_settings/notes/hg.md"
alias ubuntunotes="e ~/unix_settings/notes/ubuntu.md"
alias emacsnotes="e ~/unix_settings/notes/emacs.md"
alias brewnotes="e ~/unix_settings/notes/brew.md"
alias moveitnotes="e ~/unix_settings/notes/moveit.md"
alias gdbnotes="e ~/unix_settings/notes/gdb.md"
alias rosnotes="e ~/unix_settings/notes/ros.md"
alias baxternotes="e ~/unix_settings/notes/baxter.md"
alias macnotes="e ~/unix_settings/notes/mac.md"
alias bloomnotes="e ~/unix_settings/notes/bloom.md"